-- ID Graph: Maps first-party IDs to bidder-specific IDs
CREATE TABLE IF NOT EXISTS id_graph_mappings (
    id BIGSERIAL PRIMARY KEY,

    -- Identifiers
    fpid VARCHAR(255) NOT NULL,
    bidder_code VARCHAR(100) NOT NULL,
    bidder_uid VARCHAR(500) NOT NULL,

    -- Tracking
    first_seen TIMESTAMP NOT NULL DEFAULT NOW(),
    last_seen TIMESTAMP NOT NULL DEFAULT NOW(),
    sync_count INTEGER NOT NULL DEFAULT 1,

    -- Privacy
    consent_given BOOLEAN DEFAULT TRUE,
    gdpr_applies BOOLEAN DEFAULT FALSE,

    -- Fraud detection (hashed, not PII)
    ip_hash VARCHAR(64),
    user_agent_hash VARCHAR(64),

    -- Metadata
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    -- Unique constraint: one mapping per FPID+bidder
    UNIQUE(fpid, bidder_code)
);

-- Indexes for performance
CREATE INDEX idx_id_graph_fpid ON id_graph_mappings(fpid);
CREATE INDEX idx_id_graph_bidder ON id_graph_mappings(bidder_code, bidder_uid);
CREATE INDEX idx_id_graph_last_seen ON id_graph_mappings(last_seen);

-- Comments for documentation
COMMENT ON TABLE id_graph_mappings IS 'Maps first-party identifiers to bidder-specific user IDs';
COMMENT ON COLUMN id_graph_mappings.fpid IS 'First-party identifier generated by SDK';
COMMENT ON COLUMN id_graph_mappings.bidder_uid IS 'Bidder-specific user ID from cookie sync';
COMMENT ON COLUMN id_graph_mappings.sync_count IS 'Number of times this mapping has been updated';
