-- ============================================================
-- Migration 010: User Sync Storage
-- ============================================================
-- Store bidder-specific user IDs (cookie sync UIDs) in database
-- instead of relying on HTTP cookies for better persistence
-- ============================================================

-- Drop table if exists (for clean migrations)
DROP TABLE IF EXISTS user_syncs CASCADE;

-- Create user_syncs table
CREATE TABLE user_syncs (
    id SERIAL PRIMARY KEY,
    fpid VARCHAR(255) NOT NULL,           -- First-party ID from SDK/cookie
    bidder_code VARCHAR(50) NOT NULL,     -- e.g., 'rubicon', 'kargo', 'sovrn'
    bidder_uid VARCHAR(255),              -- UID from bidder (NULL until synced)
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,               -- Track when UID was last used in bid request
    expires_at TIMESTAMP,                 -- UID expiration (typically 90 days)

    CONSTRAINT unique_fpid_bidder UNIQUE(fpid, bidder_code)
);

-- Add foreign key to bidders table
ALTER TABLE user_syncs
ADD CONSTRAINT fk_user_syncs_bidder
FOREIGN KEY (bidder_code) REFERENCES bidders(bidder_code) ON DELETE CASCADE;

-- Create indexes for fast lookups
CREATE INDEX idx_user_syncs_fpid ON user_syncs(fpid);
CREATE INDEX idx_user_syncs_bidder ON user_syncs(bidder_code);
CREATE INDEX idx_user_syncs_expires ON user_syncs(expires_at) WHERE expires_at IS NOT NULL;

-- Create index for cleanup queries
CREATE INDEX idx_user_syncs_updated_at ON user_syncs(updated_at);

COMMENT ON TABLE user_syncs IS 'Stores bidder-specific user IDs from cookie sync for persistent user matching';
COMMENT ON COLUMN user_syncs.fpid IS 'First-party identifier generated by SDK';
COMMENT ON COLUMN user_syncs.bidder_code IS 'Bidder code (must match bidders.bidder_code)';
COMMENT ON COLUMN user_syncs.bidder_uid IS 'User ID from bidder (populated via /setuid callback)';
COMMENT ON COLUMN user_syncs.synced_at IS 'When sync was initiated';
COMMENT ON COLUMN user_syncs.updated_at IS 'When UID was last updated';
COMMENT ON COLUMN user_syncs.last_used_at IS 'When UID was last included in a bid request';
COMMENT ON COLUMN user_syncs.expires_at IS 'When sync expires (NULL = no expiration)';
